Aqi calcs ellen
NSAPH/NSAPHutils pull request #9
Opened 2022-02-17 19:07 UTC by EllenConsidine

Creation of aqi_equation function

2022-02-20 20:17 UTC, daniellebraun commented
thanks @EllenConsidine i wonder if this is related to @mmcentre (couldn't tag Misha for some reason?)

2022-02-20 20:23 UTC, mmcentre commented
Hi @daniellebraun , not sure I understand your question. mmcentre is my github username.
Best regards, Misha

2022-02-20 20:29 UTC, daniellebraun commented
sorry it was weird and didnt appear like a tag so wasnt sure it actually tagged you, in any case i saw AQI and thought of your pipelines and how they may be synergetic with @EllenConsidine 's work

2022-02-22 20:19 UTC, Naeemkh commented
@daniellebraun This PR is part of our plan to collect all helpful R functions under the NSAPHUtils package. I think you confused it with the Python version of the NSAPHUtils.

2022-02-22 20:25 UTC, Naeemkh requested changes

2022-02-22 20:25 UTC, Naeemkh commented on R/aqi_equation.R
> +#'
@EllenConsidine Please add an example and let us know how to test the function.

2022-02-22 20:25 UTC, Naeemkh commented on R/aqi_equation.R
> +#'
Please add  description of the function after "#' @description" description tag.

2022-02-22 20:25 UTC, Naeemkh commented on R/aqi_equation.R
> +PM25.Class<- c("Good", "Moderate", "Unhealthy for Sensitive Groups",
If these values are permanent, you can move them inside the function. Later on we can either create a global variable or move them into another function.

2022-02-22 20:25 UTC, daniellebraun commented
i think i was just pointing the fact that @mmcentre might already have this helpful function for AQI

2022-02-22 20:36 UTC, Naeemkh commented
> i think i was just pointing the fact that @mmcentre might already have this helpful function for AQI

In Python, right?

2022-02-22 23:33 UTC, daniellebraun commented
> > i think i was just pointing the fact that @mmcentre might already have this helpful function for AQI
> 
> In Python, right?

yes, i guess so, but i will let him confirm

2022-02-23 12:32 UTC, Naeemkh commented
That is OK. We are planning to collect all individual functions. We will address the duplicates later.

2022-02-24 13:33 UTC, Naeemkh requested changes

2022-02-24 13:33 UTC, Naeemkh commented on R/aqi_equation.R
> +#' @title Calculate Air Quality Index (AQI) and classification
classification --> Classification

2022-02-24 13:33 UTC, Naeemkh commented on R/aqi_equation.R
> +#' @author Ellen Considine
Please put @author after description field.

2022-02-24 13:33 UTC, Naeemkh commented on R/aqi_equation.R
> +  PM25.Conc_high<- c(12.099999, 35.499999, 55.499999, 150.499999, 250.499999, 5000)
More than 80 char per line. Please break it down into two lines.

2022-02-24 13:33 UTC, Naeemkh commented on R/aqi_equation.R
> +  ## Note: the reference said that AQI values >300 are calculated using 1-hour ozone breakpoints...
More than 80 char per line. Please break it down into two lines.

2022-02-24 13:46 UTC, Naeemkh approved these changes

2022-02-24 13:46 UTC, merged